### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by a-fro** [vasi/migrate_process_file#1]
Thanks for your article and example, Dave! Unfortunately, I can't get it to work. I notice that there are a couple of discrepancies between the readme and example. In the readme, you have:

```
process:
      field_image:
        - source: uri_field
          plugin: migrate_process_file
```

While in the example you have:

```
field_image:
    - source: image/original
      plugin: skip_on_empty
      method: process
    - plugin: file_import
```

Any advice on getting it working with a migration? I've tried various combinations, but it doesn't seem to enter the `transform` method of the FileImport plugin class.
